[supabase]
   url = "https://jgkcabqwqlqyxhocwime.supabase.co"
   key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impna2NhYnF3cWxxeXhob2N3aW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTkxNzgsImV4cCI6MjA2MzI5NTE3OH0.R1xdcSuHo3g7W31mb_Jm7pjlBivas0bID_6KOjoTNI8"

[gemini]
   api_key = "AIzaSyCijMNrHtZt78_PmAAHSdxt3HXKYYeJ0Zc"